export enum FeatureRoutes {
  HOME= 'home',
  CSS_BASICS = 'css-basics',
  CSS_SELECTORS = 'css-selectors',
  CSS_PSEUDO_SELECTORS = 'css-pseudo-selectors',
  CSS_FUNCTIONAL_PSEUDO_SELECTORS = 'css-functional-pseudo-selectors',
  CSS_PSEUDO_ELEMENTS = 'css-pseudo-elements',
  SCSS_VARIABLES_NESTING = 'scss-variables-nesting',
  SCSS_MIXINS = 'scss-mixins',
  SCSS_FUNCTIONS = 'scss-functions',
  SCSS_PARTIALS = 'scss-partials',
  LAYOUT_MEDIA_QUERIES = 'layout-media-queries',
  BOOTSTRAP = 'bootstrap',
  ANGULAR_STYLING = 'angular-styling',
}
